### ISSUE TITLE
Error on first use.

### ISSUE THREAD

**Issue by bearbin** [mwgg/tsar#1]
When I ran the tsar command an error was produced:

```
date: invalid date ‘14/05/16 -60 months’
```

**Comment by mwgg** [comment]
Hi,

This looks to be an issue of a particular implementation of "date" on your system. What OS are you running it on?

**Comment by bearbin** [comment]
debian 8

**Comment by mwgg** [comment]
Should be fixed now with 257bff2. Thanks for letting me know!
