### ISSUE TITLE
tsar.sh -d without -v exits due to echo_verbose refactoring

### ISSUE THREAD

**Issue by maertsen** [mwgg/tsar#7]
0f14bfa984e54e1307433f6a2f3333c9f50fc56c removed the `if` keyword in front of the `[ "$VERBOSE" -eq 1 ]` statements. Because this check has a negative return code when `$VERBOSE=0` and `set -e` is used, the script exits prematurely upon the first use of `echo_verbose`.

**Comment by cipy** [comment]
then it blows up again (also due to `set -e`) at 

`((FILES_TO_DELETE++))` which it shall actually be `((++FILES_TO_DELETE))`

**Comment by nathanjrobertson** [comment]
The fix for this issue was merged today. We now explicitly return 0 from that function.
